### ISSUE TITLE
pymiproxy not in requirements.txt

### ISSUE THREAD

**Issue by ztgrace** [thomaspatzke/WASE#1]
It looks like the `pymiproxy` requirement for WASEProxy.py isn't in requirements.txt. Let me know if you'd like a PR to add pymiproxy to the current file or a separate requirements file for the proxy.

```
# pip install -r requirements.txt
# ./WASEProxy.py -h
Traceback (most recent call last):
  File "./WASEProxy.py", line 4, in <module>
    from miproxy.proxy import ProxyHandler, MitmProxy, AsyncMitmProxy
ImportError: No module named miproxy.proxy
```

**Comment by thomaspatzke** [comment]
Thanks for pointing this out! A PR with a separate requirements file would be nice.

**Comment by ztgrace** [comment]
Thanks for publishing this project, these tools are awesome. I was just thinking about building something similar when I came across it.

I just made a PR #2 to add the requirements file with some installation instructions in the README.md.

**Comment by thomaspatzke** [comment]
Nice to hear :) Thanks for the PR!
