### ISSUE TITLE
TCP port exhaustion

### ISSUE THREAD

**Issue by jskiba99** [thomaspatzke/WASE#4]
When enabling the plugin and sending multiple burp requests to elasticsearch via context window, each request will cause a new http requests to be made from the burp client to the elasticsearch server. The tcp connection will not be torn down and will sit in a wait state after data has been sent. This leads to port tcp port exhaustion on the client and server. Is there a way to resolve this or do some type of connection pooling so the http requests go over a single tcp connection? I didn't find anything so far but I'm new to ES so I may be missing something. My ES install is a clean 16.04 ubuntu, and client is windows server 2012.

**Comment by thomaspatzke** [comment]
Fixed by commit b8c70f68d4843bf019748b73610bf1ee970519bf - now using one bulk operation instead  of individual ones.
