### ISSUE TITLE
"OnlyResp" Conf value will always return True

### ISSUE THREAD

**Issue by jskiba99** [thomaspatzke/WASE#7]
In this line the expression will always return true since the default value is true and the configuration value, while a bool initially,  is converted to a string "True" or "False" at conf save and restoration.

https://github.com/thomaspatzke/WASE/blob/b8c70f68d4843bf019748b73610bf1ee970519bf/ElasticBurp.py#L52

The value needs to be changed from string "True"/"False" to bool True/False. Is it better to include another library (distutils.util.strtobool()) or add a helper function for this purpose?

*Actually I think the code also needs changed in that before it was checking for None the defaulting to True. Now if the first is True/False and "or True" it will also always return True even if str2bool is fixed.

**Comment by thomaspatzke** [comment]
Found another way. State is now stored as int 0 or 1 which is casted correctly into bool. In addition doing recognition of setting of previous version with correct handling.

Fixed in commit 351e37234a148035016eae0c6183c311b6092c55
